Code Review v1.0
railroadmedia/Pianote2 pull request #10
Opened 2021-03-05 18:58 UTC by calebfavor

2021-03-08 14:22 UTC, bogdan-vol requested changes

2021-03-08 14:22 UTC, bogdan-vol commented on src/views/onboard/Login.js
> +const isNotch = DeviceInfo.hasNotch();
I can't think of a functionality in the app that needs this. In this particular component SafeAreaView would be enough.

2021-03-19 17:04 UTC, bogdan-vol requested changes

2021-04-20 07:39 UTC, csillaj requested changes

2021-04-21 08:36 UTC, kp-98 commented on index.js
> +global.isPackOnly = false;
complete

2021-04-21 08:36 UTC, kp-98 commented on src/components/ContinueIcon.js
> +          return 25;
complete - although my code editor isnt a fan of the single line fragment, but still got rid of else

2021-04-21 08:36 UTC, kp-98 commented on src/components/CustomSwitch.js
> +    if (this.state.clicked == false) {
done throughout app

2021-04-21 08:37 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +          ? this.state.items[i].like_count + 1
nice solution, implemented number 1 throughout the app

2021-04-21 08:38 UTC, kp-98 commented on src/components/MoreInfoIcon.js
> +  static navigationOptions = { header: null };
complete with <LongButton in refactor_code branch

2021-04-21 08:40 UTC, kp-98 commented on src/views/content/VideoPlayer.js
>  export default class VideoPlayer extends React.Component {
done

2021-04-21 08:51 UTC, kp-98 commented on src/views/content/VideoPlayer.js
> +                          {global.isConnected && (
got rid of

2021-04-21 08:51 UTC, kp-98 commented on src/views/content/VideoPlayerSong.js
> +  static contextType = NetworkContext;
complete

2021-04-21 08:52 UTC, kp-98 commented on src/views/onboard/Login.js
> +  changeColor(number) {
complete

2021-04-21 09:00 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +                {Platform.OS === 'ios' ? (
complete

2021-04-21 09:01 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +                  {!this.props.hideFilterButton && (
fixed

2021-04-21 09:02 UTC, kp-98 commented on src/views/onboard/CreateAccount2.js
> +                <View style={{ height: 27.5 }} />
agreed, outside of onboard routes i got rid oflike 90%, but will fix onboard

2021-04-21 09:03 UTC, kp-98 commented on src/views/onboard/GetRestarted.js
> +  static navigationOptions = { header: null };
deleted, was originally planned for, never used

2021-04-22 00:14 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +  componentWillReceiveProps = props => {
merge with bogdan's request for this

2021-04-22 00:17 UTC, kp-98 commented on src/components/NavMenuHeaders.js
> +                    this.props.currentPage == 'LESSONS'
complete, nice call

2021-04-22 00:28 UTC, kp-98 commented on src/modals/ContentModal.js
> +        typeof this.props.data.type !== 'undefined' ? this.props.data.type : '',
complete

2021-04-22 00:28 UTC, kp-98 commented on src/modals/PasswordMatch.js
> +  static navigationOptions = { header: null };
merge w bogdans review

2021-04-22 00:35 UTC, kp-98 commented on src/views/onboard/Login.js
> +const isNotch = DeviceInfo.hasNotch();
complete

2021-04-22 00:37 UTC, kp-98 commented on src/views/onboard/WelcomeBack.js
> +export default class WelcomeBack extends React.Component {
planned never used unfortunately same as get restarted

2021-04-22 00:37 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +          {!this.props.hideSeeAll && (
merge with bogdans / redo horizontal / vertical

2021-04-22 00:43 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +      isPaging: false,
merge with bogdans / redo horizontal / vertical

2021-04-22 01:11 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +          <View style={{ flex: 1 }} />
done, got rid of every one that made sense to get rid of, now the only <View style={{xxx}}} /> left are used when needed to offset something equally, example on profile header. Removed this pattern from almost everywhere

2021-04-22 01:12 UTC, kp-98 commented on src/views/onboard/CreateAccount2.js
> +                <View style={{ height: 27.5 }} />
completed, there should be almost zero instances of this in the app now

2021-04-22 01:19 UTC, kp-98 commented on src/views/onboard/Login.js
> +          <View style={{ height: '20%' }} />
completed

2021-04-22 01:19 UTC, kp-98 commented on src/views/onboard/Login.js
> +const isNotch = DeviceInfo.hasNotch();
fixed

2021-04-22 01:20 UTC, kp-98 commented on src/components/ContinueIcon.js
> +export default withNavigation(ContinueIcon);
merged into one new component, <LongButton

2021-04-22 01:20 UTC, kp-98 commented on src/views/content/Course.js
> +      filtering: false, // filtering
complete

2021-04-22 01:22 UTC, kp-98 commented on src/components/CustomSwitch.js
> +          <View style={{ flex: 1 }} />
complete

2021-04-22 01:23 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +        this.state.items[i].isAddedToList = true;
complete

2021-04-22 01:23 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +        this.state.items[i].isLiked = !this.state.items[i].isLiked;
complete

2021-04-22 01:24 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +          <View style={{ flex: 3 }} />
complete

2021-04-22 01:24 UTC, kp-98 commented on src/components/MoreInfoIcon.js
> +export default withNavigation(MoreInfoIcon);
merged into longbutton

2021-04-22 01:25 UTC, kp-98 commented on src/components/NavigationBar.js
> +          <View style={localStyles.navContainer}>
complete

2021-04-22 01:25 UTC, kp-98 commented on src/components/NavigationBar.js
> +          <View style={localStyles.navContainer}>
i think

2021-04-22 01:26 UTC, kp-98 commented on src/components/NavigationMenu.js
> +            <View style={{ flex: 1 }} />
fixed

2021-04-22 01:27 UTC, kp-98 commented on src/components/NavigationMenu.js
> +            <View style={{ flex: 1 }} />
fixed

2021-04-22 01:27 UTC, kp-98 commented on src/components/NextVideo.js
> +        <View style={{ height: 7.5 }} />
fixed

2021-04-22 01:28 UTC, kp-98 commented on src/components/NextVideo.js
> +              <View style={{ flex: 1 }} />
fixed

2021-04-22 01:30 UTC, kp-98 commented on src/components/SoundSlice.js
> +export default withNavigation(SoundSlice);
fixed

2021-04-22 01:31 UTC, kp-98 commented on src/components/StartIcon.js
> +export default withNavigation(StartIcon);
moved into <LongButton

2021-04-22 01:32 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +        this.state.items[i].isLiked = !this.state.items[i].isLiked;
fixed

2021-04-22 01:33 UTC, kp-98 commented on src/modals/AssignmentComplete.js
> +const factor = (height / 812 + width / 375) / 2;
complte

2021-04-22 01:34 UTC, kp-98 commented on src/modals/ContentModal.js
> +  removeFromMyList = contentID => {
complete

2021-04-22 02:02 UTC, kp-98 commented on src/modals/Loading.js
> +/**
complete

2021-04-22 02:03 UTC, kp-98 commented on src/modals/LogOut.js
> +      chosenInstructor: 2
complete

2021-04-22 02:03 UTC, kp-98 commented on src/modals/LogOut.js
> +    await this.props.navigation.dispatch(resetAction);
complete

2021-04-22 02:04 UTC, kp-98 commented on src/modals/PasswordMatch.js
> +const factor = (height / 812 + width / 375) / 2;
complete

2021-04-22 02:05 UTC, kp-98 commented on src/modals/ProfileImage.js
> +const factor = (height / 812 + width / 375) / 2;
complete

2021-04-22 02:43 UTC, kp-98 commented on src/views/user/ProfileSettings.js
> +const factor = (height / 812 + width / 375) / 2;
complete

2021-04-22 02:43 UTC, kp-98 commented on src/views/user/ProfileSettings.js
> +    this.state = {
complete

2021-04-22 02:44 UTC, kp-98 commented on src/views/user/ProfileSettings.js
> +    const { response, error } = await userForgotPassword({ email });
complete

2021-04-22 02:45 UTC, kp-98 commented on src/views/user/ProfileSettings.js
> +        } else if (response.error) {
complete

2021-04-22 02:46 UTC, kp-98 commented on src/views/user/ProfileSettings.js
> +const factor = (height / 812 + width / 375) / 2;
complete

2021-04-22 03:47 UTC, kp-98 commented on src/views/onboard/CreateAccount3.js
> +  render() {
complete 80% of this one, createaccount3 never got refactored, will finish the rest of the blank views

2021-04-26 06:48 UTC, csillaj commented on src/components/ContinueIcon.js
> +          return 25;
Remove "else"  from HorizontalList decideWidth method too

2021-04-26 06:58 UTC, csillaj commented on src/views/onboard/Login.js
> +const isNotch = DeviceInfo.hasNotch();
NavigationMenu, CommentSort, ReplyNotification, Assignement, ViewLesson components are still using DeviceInfo.hasNotch()

2021-04-26 07:01 UTC, csillaj commented on src/components/HorizontalVideoList.js
> +                {Platform.OS === 'ios' ? (
SongCatalog, VIewLesson, CreateAccount, CreateAccount2, LoadPage, ResetPassword and Terms components still have  Platform.OS == 'android' condition

2021-05-03 04:26 UTC, kp-98 commented on src/views/onboard/LoginCredentials.js
> +        ['loggedIn', 'true'],
done

2021-05-03 05:06 UTC, kp-98 commented on src/views/onboard/Login.js
>  }
got rid of most

2021-05-03 05:13 UTC, kp-98 commented on src/views/content/Course.js
> +      started: true, // if started lesson
complete across app

2021-05-03 05:14 UTC, kp-98 commented on src/views/content/Course.js
> +        !this.firstTimeFocused ? (this.firstTimeFocused = true) : this.refresh()
complete

2021-05-03 05:15 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +          horizontal={this.props.isTile ? false : true}
merge with rewrite card component

2021-05-03 05:22 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +    this._onOrientationDidChange = this._onOrientationDidChange.bind(this);
fixed

2021-05-03 05:23 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +    Orientation.addOrientationListener(this._onOrientationDidChange);
fixed

2021-05-03 05:29 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +  _onOrientationDidChange = () => {
fixed

2021-05-03 05:30 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +  componentWillReceiveProps = props => {
merged with fix lists

2021-05-03 05:42 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +  changeType = word => {
complete

2021-05-03 05:42 UTC, kp-98 commented on src/components/NavigationBar.js
> +      onMain: false,
fixed

2021-05-03 05:47 UTC, kp-98 commented on src/components/NavigationBar.js
> +      secondaryColor: this.props.isMethod
it is this now ```secondaryColor: this.props.isMethod
        ? colors.pianoteGrey
        : colors.secondBackground,```

2021-05-03 06:02 UTC, kp-98 commented on src/components/NavMenuHeaders.js
>  import Pianote from 'Pianote2/src/assets/img/svgs/pianote.svg';
fixed

2021-05-03 06:36 UTC, kp-98 commented on src/modals/LessonComplete.js
> +  changeType = word => {
fixed

2021-05-03 06:45 UTC, kp-98 commented on src/modals/ReplyNotification.js
> +    this.setState({ statusChange });
fixed

2021-05-03 07:14 UTC, kp-98 commented on src/modals/ReplyNotification.js
> +    marginBottom: DeviceInfo.hasNotch() ? 20 : 0,
fixed

2021-05-03 07:14 UTC, kp-98 commented on src/modals/RestartCourse.js
> +  changeType = word => {
fixed

2021-05-03 07:15 UTC, kp-98 commented on src/views/user/Profile.js
>  import Settings from 'Pianote2/src/assets/img/svgs/settings.svg';
fixed

2021-05-03 20:28 UTC, kp-98 commented on src/views/user/ProfileSettings.js
> +    fontSize: DeviceInfo.isTablet() ? 20 : 16,
complete, good idea

2021-05-03 20:29 UTC, kp-98 commented on src/views/user/ProfileSettings.js
> +});
complete, good call

2021-05-03 20:48 UTC, kp-98 commented on src/views/user/Settings.js
> +import { getUserData } from 'Pianote2/src/services/UserDataAuth.js';
complete

2021-05-03 21:07 UTC, kp-98 commented on src/views/user/Settings.js
> +      showLogOut: false
complete

2021-05-03 21:11 UTC, kp-98 commented on src/views/user/Support.js
> +import { getUserData } from 'Pianote2/src/services/UserDataAuth.js';
complete

2021-05-04 01:29 UTC, kp-98 commented on src/views/content/Course.js
> +      outVideos: false,
merge into rewrite cards

2021-05-04 01:35 UTC, kp-98 commented on src/views/content/Course.js
> +      page: 1,
left in state for now, sometimes state update required when paging

2021-05-04 01:36 UTC, kp-98 commented on src/views/user/Profile.js
> +  turnOfffNotifications = async data => {
fixed across app

2021-05-04 01:44 UTC, kp-98 commented on src/views/user/Profile.js
> +  'lesson comment reply': [
complete

2021-05-04 01:45 UTC, kp-98 commented on src/modals/XpRank.js
> +    fontSize: DeviceInfo.isTablet() ? 18 : 14
fixed on all app

2021-05-04 01:51 UTC, kp-98 commented on src/modals/ReplyNotification.js
> +    this.state = {
complete

2021-05-04 01:51 UTC, kp-98 commented on src/modals/ReplyNotification.js
> +  'lesson comment reply': [
complete

2021-05-04 01:52 UTC, kp-98 commented on src/modals/ContentModal.js
> +  changeType = word => {
complete

2021-05-04 01:55 UTC, kp-98 commented on src/modals/ContentModal.js
> +  componentDidMount = () => {
fixed

2021-05-04 01:56 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +                <View style={[styles.centerContent, { flex: 1 }]}>
merge with cards

2021-05-04 01:56 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +                  <View style={{ flex: 2.5 }} />
complete

2021-05-04 01:57 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +  changeType = word => {
fixed

2021-05-04 01:57 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +  componentWillReceiveProps = props => {
issue fixed by refactor cards

2021-05-04 02:00 UTC, kp-98 commented on src/components/SoundSlice.js
> +import IdleTimerManager from 'react-native-idle-timer';
im not sure i understand this issue, but it should be complete

2021-05-04 02:00 UTC, kp-98 commented on src/components/ResetIcon.js
> +export default withNavigation(ResetIcon);
merged LongButton

2021-05-04 02:03 UTC, kp-98 commented on src/components/Replies.js
> +                  <View>{this.mapReplies()}</View>
complete

2021-05-04 02:04 UTC, kp-98 commented on src/components/Replies.js
> +      () => setTimeout(callback || (() => {}), 0)
skip for now

2021-05-04 02:05 UTC, kp-98 commented on src/components/NavigationMenu.js
> +    paddingBottom: DeviceInfo.hasNotch() ? 30 : 10
fixed

2021-05-04 02:05 UTC, kp-98 commented on src/components/NavigationMenu.js
> +    paddingTop: DeviceInfo.hasNotch() ? 50 : 30,
fixed

2021-05-04 02:05 UTC, kp-98 commented on src/components/NavigationBar.js
> +      primaryColor: this.props.isMethod ? colors.pianoteRed : 'white'
fixed

2021-05-04 02:51 UTC, kp-98 commented on src/components/NavigationBar.js
>  import MaterialIcon from 'react-native-vector-icons/MaterialCommunityIcons';
complete

2021-05-04 02:51 UTC, kp-98 commented on src/components/NavMenuHeaders.js
> +import NavigationMenu from 'Pianote2/src/components/NavigationMenu.js';
complete

2021-05-04 02:51 UTC, kp-98 commented on src/components/Replies.js
>  import MaterialIcon from 'react-native-vector-icons/MaterialCommunityIcons';
complete

2021-05-04 02:51 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +import FontIcon from 'react-native-vector-icons/FontAwesome5';
complete

2021-05-04 02:51 UTC, kp-98 commented on src/modals/ReplyNotification.js
> +import FontAwesome from 'react-native-vector-icons/FontAwesome';
complete

2021-05-04 02:52 UTC, kp-98 commented on src/views/user/Profile.js
> +import AntIcon from 'react-native-vector-icons/AntDesign';
complete

2021-05-04 02:52 UTC, kp-98 commented on src/views/user/ProfileSettings.js
>  import EntypoIcon from 'react-native-vector-icons/Entypo';
complete

2021-05-04 02:52 UTC, kp-98 commented on src/views/user/Settings.js
>  import FontIcon from 'react-native-vector-icons/FontAwesome';
complete

2021-05-04 02:52 UTC, kp-98 commented on src/views/content/Course.js
> +const isCloseToBottom = ({ layoutMeasurement, contentOffset, contentSize }) => {
merge with fix cards

2021-05-04 02:56 UTC, kp-98 commented on src/views/content/Course.js
> +    let items = [];
fixed

2021-05-04 03:08 UTC, kp-98 commented on src/views/user/Support.js
> +    return (
complete

2021-05-04 03:09 UTC, kp-98 commented on src/views/user/ProfileSettings.js
> +  render() {
complete

2021-05-04 07:47 UTC, kp-98 commented on src/views/content/Course.js
> +  windowDim.width < windowDim.height ? windowDim.width : windowDim.height;
fixed

2021-05-04 07:52 UTC, kp-98 commented on src/modals/XpRank.js
> +  constructor(props) {
complete

2021-05-04 19:45 UTC, kp-98 commented on src/modals/CheckEmail.js
> +export default withNavigation(CheckEmail);
fixed

2021-05-04 23:14 UTC, kp-98 commented on src/views/onboard/Login.js
>  }
fixed, didnt change across app, might be better to talk on that one

2021-05-04 23:31 UTC, kp-98 commented on src/components/CustomSwitch.js
> +export default withNavigation(CustomSwitch);
youre right this --> useNativeDriver: true works really well, thanks

2021-05-05 01:31 UTC, kp-98 commented on src/components/NavMenuHeaders.js
> +  View,
complete

2021-05-05 01:32 UTC, kp-98 commented on src/components/NavigationMenu.js
> +        <View style={{ alignSelf: 'center' }}>
done

2021-05-05 01:34 UTC, kp-98 commented on src/components/NavigationMenu.js
> +      <View
done

2021-05-05 01:35 UTC, kp-98 commented on src/components/NextVideo.js
> +        <View style={{ width: '100%' }}>
complete

2021-05-05 01:38 UTC, kp-98 commented on src/components/NextVideo.js
> +          </View>
done

2021-05-05 01:42 UTC, kp-98 commented on src/components/NextVideo.js
> +            <View
fixed

2021-05-05 01:42 UTC, kp-98 commented on src/components/NextVideo.js
> +    width: DeviceInfo.isTablet()
fixed

2021-05-05 01:42 UTC, kp-98 commented on src/components/Replies.js
> +                <View style={{ flex: 1 }}>
fixed

2021-05-05 01:43 UTC, kp-98 commented on src/components/Replies.js
> +                  <View style={{ width: '100%', zIndex: 5 }}>
fixed

2021-05-05 01:44 UTC, kp-98 commented on src/components/Replies.js
> +                            <View style={{ flexDirection: 'row' }}>
left

2021-05-05 01:44 UTC, kp-98 commented on src/components/Replies.js
> +                        <View style={{ flexDirection: 'row' }}>
left

2021-05-05 01:45 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +      outVideos: this.props.outVideos,
merge with fix card component

2021-05-05 01:45 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +      showRelevance: false,
merge with refactor cards

2021-05-05 01:45 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +      isLoading: this.props.isLoading,
merge with fix cards

2021-05-05 01:45 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +      isPaging: false,
merge with fix cards

2021-05-05 01:45 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +  showSpinner = () => {
merge with fix cards

2021-05-05 01:46 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +          <View
merge with fix cards

2021-05-05 01:46 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +                <View
merge with fix cards

2021-05-05 01:46 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +              <View
merge with fix cards

2021-05-05 01:48 UTC, kp-98 commented on src/modals/AddToCalendar.js
> +        <View style={[styles.container, styles.centerContent]}>
done

2021-05-05 01:49 UTC, kp-98 commented on src/modals/AssignmentComplete.js
> +            <View style={[styles.centerContent]}>
complete

2021-05-05 01:55 UTC, kp-98 commented on src/modals/AssignmentComplete.js
> +            <View
complete

2021-05-05 01:56 UTC, kp-98 commented on src/modals/AssignmentComplete.js
> +            <View>
removed

2021-05-05 02:00 UTC, kp-98 commented on src/modals/CommentSort.js
> +export default withNavigation(CommentSort);
done

2021-05-05 02:01 UTC, kp-98 commented on src/modals/LogOut.js
> +  render = () => {
done

2021-05-05 02:02 UTC, kp-98 commented on src/modals/NoConnection.js
> +  render = () => {
component removed

2021-05-05 02:04 UTC, kp-98 commented on src/modals/PasswordEmailMatch.js
> +  render = () => {
complete

2021-05-05 02:04 UTC, kp-98 commented on src/modals/PasswordMatch.js
> +  render = () => {
complete

2021-05-05 02:14 UTC, kp-98 commented on src/modals/ReplyNotification.js
> +  render = () => {
reduced

2021-05-05 02:15 UTC, kp-98 commented on src/modals/XpRank.js
> +  render = () => {
done

2021-05-05 02:30 UTC, kp-98 commented on src/views/user/NotificationSettings.js
> +  render() {
multicolored safe areas so going to leave 2

2021-05-05 02:45 UTC, kp-98 commented on src/views/user/Profile.js
> +  render() {
complete

2021-05-05 03:19 UTC, kp-98 commented on src/views/user/Settings.js
> +    return (
done

2021-05-05 03:24 UTC, kp-98 commented on src/modals/ValidateEmail.js
> +  render = () => {
got rid of file

2021-05-05 03:51 UTC, kp-98 commented on src/modals/Relevance.js
> +export default withNavigation(Relevance);
done

2021-05-05 23:24 UTC, kp-98 commented on src/components/HorizontalVideoList.js
> +  removeFromMyList = contentID => {
merge with refactor lists

2021-05-05 23:24 UTC, kp-98 commented on src/components/VerticalVideoList.js
> +  removeFromMyList = contentID => {
merge with redo lists

2021-05-05 23:39 UTC, kp-98 commented on src/modals/AddToCalendar.js
> +export default withNavigation(AddToCalendar);
complete

2021-05-05 23:43 UTC, kp-98 commented on src/modals/AssignmentComplete.js
> +export default withNavigation(AssignmentComplete);
complete

2021-05-05 23:52 UTC, kp-98 commented on src/modals/DisplayName.js
> +  render = () => {
done

2021-05-05 23:54 UTC, kp-98 commented on src/modals/LessonComplete.js
> +  render = () => {
done

2021-05-05 23:55 UTC, kp-98 commented on src/modals/ProfileImage.js
> +  render = () => {
done

2021-05-06 00:32 UTC, kp-98 commented on src/modals/RestartCourse.js
> +  render = () => {
complete

2021-05-06 00:39 UTC, kp-98 commented on src/modals/ContentModal.js
> +  render = () => {
complete

2021-05-06 04:23 UTC, kp-98 commented on src/views/onboard/Login.js
>  }
done

2022-01-13 06:59 UTC, closed without merging