Live
railroadmedia/Pianote2 pull request #12
Opened 2021-05-03 01:50 UTC by kp-98

pull live into master

2021-05-06 07:52 UTC, csillaj requested changes

2021-05-10 02:27 UTC, kp-98 commented on index.js
> +global.isiOS = Platform.OS == 'ios';
changed

2021-05-10 02:27 UTC, kp-98 commented on src/modals/Live.js
> +    console.log(this.props.liveLesson[0].thumbnail_url);
done

2021-05-10 02:28 UTC, kp-98 commented on src/views/content/Course.js
> +    View,
fixed

2021-05-10 02:28 UTC, kp-98 commented on src/views/content/Lessons.js
> +                      fontSize: DeviceInfo.isTablet() ? 20 : 16,
fixed

2021-05-10 02:29 UTC, kp-98 commented on src/views/content/Lessons.js
> +                              fontSize: DeviceInfo.isTablet() ? 16 : 14,
fixed

2021-05-10 02:30 UTC, kp-98 commented on src/views/content/Live.js
> +    if (type == 'live') {
fixed

2021-05-10 02:30 UTC, kp-98 commented on src/views/content/Live.js
> +    if (type == 'live') {
fixrd

2021-05-10 02:31 UTC, kp-98 commented on src/views/content/Live.js
> +      this.state.items.find(
fixed in code_refactor, so will merge then

2021-05-10 02:31 UTC, kp-98 commented on src/views/onboard/LoadPage.js
> +import { requestTrackingPermission } from 'react-native-tracking-transparency';
removed

2021-05-10 02:33 UTC, kp-98 commented on src/views/content/Lessons.js
> +                                  ? this.state.liveLesson[0].thumbnail_url
these url's this.state.liveLesson[0].thumbnail_url were not working properly, they kept leaving blank views. Maybe you can have a look at it?

2021-05-10 13:57 UTC, bogdan-vol requested changes

2021-05-10 13:57 UTC, bogdan-vol commented on src/views/content/Live.js
> +        : response[i].published_on;
Use the `||` operator in such cases:
`let time = response[i].live_event_start_time || response[i].published_on;`

2021-05-10 13:57 UTC, bogdan-vol commented on src/views/content/Live.js
>        if (this.state.month == '' && d instanceof Date && !isNaN(d.valueOf())) {
There's no point in checking if month is equal to '' - it's been assigned that value in the constructor and not changed since. Check React's life cycle methods documentation if needed.
Delete `d instanceof Date && !isNaN(d.valueOf())` or refactor.

2021-05-10 13:57 UTC, bogdan-vol commented on src/views/content/Live.js
>        let d = new Date(date);
Why do you need both `date` and `d`.

2021-05-10 13:57 UTC, bogdan-vol commented on src/views/content/Live.js
>      let timeNow = Math.floor(Date.now() / 1000);
This component should only have a list of live events. Don't use it to display the live video and chat here. You have a component for such thing called `VideoPlayer`.

2021-05-10 13:57 UTC, bogdan-vol commented on src/views/content/Live.js
>      try {
Ditch `changeType()`. Use `textTransform: 'capitalize'` on `Text` components and replace the - at most.

2021-05-10 13:57 UTC, bogdan-vol commented on src/views/content/Live.js
>          this.setState({ month: d.getMonth() });
There can't be only one month. What if there were events on multiple months? All events have to be grouped by month and at the moment all the events are grouped into only and the same month.

2021-05-10 13:57 UTC, bogdan-vol commented on src/views/content/Live.js
> +                        {day[item.timeData.day]} {item.timeData.date}
You don't have to calculate this dates and times anymore. Use [Date.toLocaleString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString):
```
let date = new Date(`${item.live_event_start_time || item.published_on} UTC`);
...
{date.toLocaleString([], { weekday: 'short' })} {date.getDate()}
```

2021-05-10 13:57 UTC, bogdan-vol commented on src/views/content/Live.js
>                          {' ' + item.timeData.amPM}
Same as above. Don't enforce the am/pm format. Let it be taken from the user's preferences.
```
let date = new Date(`${item.live_event_start_time || item.published_on} UTC`);
...
{date.toLocaleString([], { hour: 'numeric', minute: '2-digit' })}
```

2021-05-11 03:58 UTC, kp-98 commented on src/views/content/Lessons.js
> +                                  ? this.state.liveLesson[0].thumbnail_url
ok it seems to be working now, not sure why it wasnt before, fixed

2021-05-11 03:59 UTC, kp-98 commented on src/modals/Live.js
> +                    ? this.props.liveLesson[0].thumbnail_url
fixed

2021-05-11 04:05 UTC, kp-98 commented on src/views/content/Live.js
>      try {
complete, done on code refactor too

2021-05-11 04:07 UTC, kp-98 commented on src/views/content/Lessons.js
>      let content = [await getLiveContent()];
fixed

2021-05-11 04:36 UTC, kp-98 commented on src/views/content/Live.js
> +        : response[i].published_on;
fixed

2021-05-11 06:20 UTC, kp-98 commented on src/modals/Live.js
> +                    ? this.props.liveLesson[0].thumbnail_url
fixed

2021-05-13 03:13 UTC, kp-98 commented on src/views/content/Lessons.js
>    async timer() {
fixed, extracted timer and got rid of async. it was async before because i was playing around w something and didnt change it back

2021-05-13 03:31 UTC, kp-98 commented on src/views/content/Live.js
>        if (this.state.month == '' && d instanceof Date && !isNaN(d.valueOf())) {
refactors, got rid of

2021-05-13 03:31 UTC, kp-98 commented on src/views/content/Live.js
>        let d = new Date(date);
it was a remnant from copy pasted code, deleted

2021-05-13 03:32 UTC, kp-98 commented on src/views/content/Live.js
>          this.setState({ month: d.getMonth() });
fixed

2021-05-13 05:01 UTC, kp-98 commented on src/views/content/Live.js
>                          {' ' + item.timeData.amPM}
nice didnt know of this function

2021-05-13 06:32 UTC, merged