Code refactor
railroadmedia/Pianote2 pull request #16
Opened 2021-05-13 06:33 UTC by kp-98

2021-05-13 11:07 UTC, csillaj requested changes
Some general observations @kp-98 
- use "===" and "!==" everywhere instead of "==" and "!="
- use "onTablet" global variable everywhere
- use "isIOs" global variable everywhere
- remove inline styles everywhere if possible
- use Modal from 'react-native' instead of 'react-native-modal'

2021-05-13 11:55 UTC, csillaj requested changes

2021-05-13 11:55 UTC, csillaj commented on src/components/HorizontalVideoList.js
>            return navigate('VIDEOPLAYER', {
change to 'VIEWLESSON'

2021-05-13 11:55 UTC, csillaj commented on src/views/content/Foundations.js
>      this.setState({ items: [], showRestartCourse: false });
combine the 2 setstates

2021-05-13 11:55 UTC, csillaj commented on src/views/content/Method.js
>      await resetProgress(this.state.id);
combine the 2 setstates

2021-05-13 11:55 UTC, csillaj commented on src/components/VerticalVideoList.js
>            return navigate('VIDEOPLAYER', {
change to VIEWLESSON

2021-05-13 11:55 UTC, csillaj commented on src/services/navigation.service.js
>          return navigate('VIDEOPLAYER', {
change to VIEWLESSON

2021-05-13 11:55 UTC, csillaj commented on src/services/navigation.service.js
>      return navigate('VIDEOPLAYER', {
change to VIEWLESSON

2021-05-13 11:55 UTC, csillaj commented on src/views/content/MethodLevel.js
>                navigate('VIDEOPLAYER', {
change to VIEWLESSON

2021-05-14 02:52 UTC, kp-98 commented on src/components/VerticalVideoList.js
>            return navigate('VIDEOPLAYER', {
thanks forgot about this!

2021-05-14 03:09 UTC, kp-98 commented on src/components/NavigationBar.js
>        secondaryColor: this.props.isMethod
it makes the inline code cleaner, otherwise here will be three ternary operators and its confusing to understand : ```this.props.currentPage == 'DOWNLOAD'
                    ? this.state.primaryColor
                    : this.state.secondaryColor```

2021-05-14 03:17 UTC, kp-98 commented on src/components/LongButton.js
> +    } else if (this.props.type == 'START') {
this.sizing('font') is actually used once at the bottom

2021-05-14 03:20 UTC, kp-98 commented on src/views/onboard/LoadPage.js
> +      const { email, resetKey, password, forumUrl } = data;
hmmm im confused, this already is removed...
```      
await AsyncStorage.removeItem('resetKey');
      const { email, resetKey, password, forumUrl } = data;

      if (!this.context.isConnected) {
```

2021-05-14 03:22 UTC, kp-98 commented on src/components/SoundSlice.js
> +  componentDidMount = () => IdleTimerManager.setIdleTimerDisabled(true);
makes sense now, thanks

2021-05-14 03:27 UTC, kp-98 commented on src/views/onboard/Login.js
> +    if (num == 1) {
im not sure i understand this here: "two texts"

2021-05-14 05:09 UTC, csillaj commented on src/components/LongButton.js
> +    } else if (this.props.type == 'START') {
@kp-98 what I was trying to say is that if you have a return in the if statement you dont need an else
` if (this.props.type === 'CONTINUE') {
      return (
        <Icon.Entypo
          name={'controller-play'}
          size={this.sizing('icon')}
          color={'white'}
        />
      );
    }
if (this.props.type === 'START') {
      return (
        <Icon.Entypo
          name={'controller-play'}
          size={this.sizing('icon')}
          color={'white'}
        />
      );
    }`

2021-05-14 05:22 UTC, csillaj commented on src/components/NavigationBar.js
>        secondaryColor: this.props.isMethod
You're right is makes the code cleaner but that doesn't mean it should be a state variable :)

2021-05-14 05:25 UTC, csillaj commented on src/modals/DisplayName.js
> +      <Modal
Delete the file if this Modal is not used anymore

2021-05-14 05:28 UTC, csillaj commented on src/modals/PasswordMatch.js
>        <TouchableWithoutFeedback
Delete the file if this Modal is not used anymore

2021-05-14 05:30 UTC, csillaj commented on src/modals/ProfileImage.js
> +      <Modal
Delete the file if this Modal is not used anymore

2021-05-14 05:30 UTC, kp-98 commented on src/components/LongButton.js
> +    } else if (this.props.type == 'START') {
i see what u mean, will change

2021-05-14 05:33 UTC, csillaj commented on src/views/onboard/Login.js
> +    if (num == 1) {
`  renderWords = (text1, text2) => {
      return (
          <Text style={[localStyles.bigText, localStyles.boldText]}>
            {text1}
          </Text>
          <Text style={localStyles.normalText}>{text2}</Text>
      );
    }
`
and call the function like this.renderWords('Pianote Lessons, Songs, \n& Support', 'Everywhere you go.')

2021-05-14 05:55 UTC, kp-98 commented on src/modals/DisplayName.js
> +      <Modal
done

2021-05-14 05:55 UTC, kp-98 commented on src/modals/PasswordMatch.js
>        <TouchableWithoutFeedback
done

2021-05-14 06:10 UTC, kp-98 commented on src/views/onboard/Login.js
> +    if (num == 1) {
the issue with this is that each of the 5 places has its text broken at a different part to make the text bold, so i think its best if we leave it as is

2021-05-16 06:01 UTC, merged